package _227._100._168._192._6888.ormrpc.services.wsgeneratepaymentfacade;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * WSGeneratePaymentFacadeSrvProxyService service = new WSGeneratePaymentFacadeSrvProxyService();
 * WSGeneratePaymentFacadeSrvProxy portType = service.getWSGeneratePaymentFacade();
 * portType.generatePayment(...);
 * </pre>
 * 
 * </p>
 */
@WebServiceClient(name = "WSGeneratePaymentFacadeSrvProxyService", targetNamespace = "http://192.168.100.227:6888/ormrpc/services/WSGeneratePaymentFacade", wsdlLocation = "http://192.168.100.227:6888/ormrpc/services/WSGeneratePaymentFacade?wsdl")
public class WSGeneratePaymentFacadeSrvProxyService extends Service {

    private final static URL WSGENERATEPAYMENTFACADESRVPROXYSERVICE_WSDL_LOCATION;

    private final static Logger logger = Logger
            .getLogger(_227._100._168._192._6888.ormrpc.services.wsgeneratepaymentfacade.WSGeneratePaymentFacadeSrvProxyService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = _227._100._168._192._6888.ormrpc.services.wsgeneratepaymentfacade.WSGeneratePaymentFacadeSrvProxyService.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.100.227:6888/ormrpc/services/WSGeneratePaymentFacade?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.100.227:6888/ormrpc/services/WSGeneratePaymentFacade?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSGENERATEPAYMENTFACADESRVPROXYSERVICE_WSDL_LOCATION = url;
    }

    public WSGeneratePaymentFacadeSrvProxyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSGeneratePaymentFacadeSrvProxyService() {
        super(WSGENERATEPAYMENTFACADESRVPROXYSERVICE_WSDL_LOCATION, new QName("http://192.168.100.227:6888/ormrpc/services/WSGeneratePaymentFacade",
                "WSGeneratePaymentFacadeSrvProxyService"));
    }

    /**
     * @return
     *         returns WSGeneratePaymentFacadeSrvProxy
     */
    @WebEndpoint(name = "WSGeneratePaymentFacade")
    public WSGeneratePaymentFacadeSrvProxy getWSGeneratePaymentFacade() {
        return super.getPort(new QName("http://192.168.100.227:6888/ormrpc/services/WSGeneratePaymentFacade", "WSGeneratePaymentFacade"),
                WSGeneratePaymentFacadeSrvProxy.class);
    }

}
