package _227._100._168._192._6888.ormrpc.services.wsgeneratepaymentfacade;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 */
@WebService(name = "WSGeneratePaymentFacadeSrvProxy", targetNamespace = "http://192.168.100.227:6888/ormrpc/services/WSGeneratePaymentFacade")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WSGeneratePaymentFacadeSrvProxy {

    /**
     * @param params
     * @return
     *         returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "generatePaymentReturn", partName = "generatePaymentReturn")
    public String generatePayment(@WebParam(name = "params", partName = "params") String params);

}
