package _227._100._168._192._6888.ormrpc.services.easlogin;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * EASLoginProxyService service = new EASLoginProxyService();
 * EASLoginProxy portType = service.getEASLogin();
 * portType.login(...);
 * </pre>
 * 
 * </p>
 */
@WebServiceClient(name = "EASLoginProxyService", targetNamespace = "http://192.168.100.227:6888/ormrpc/services/EASLogin", wsdlLocation = "http://192.168.100.227:6888/ormrpc/services/EASLogin?wsdl")
public class EASLoginProxyService extends Service {

    private final static URL EASLOGINPROXYSERVICE_WSDL_LOCATION;

    private final static Logger logger = Logger.getLogger(_227._100._168._192._6888.ormrpc.services.easlogin.EASLoginProxyService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = _227._100._168._192._6888.ormrpc.services.easlogin.EASLoginProxyService.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.100.227:6888/ormrpc/services/EASLogin?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.100.227:6888/ormrpc/services/EASLogin?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EASLOGINPROXYSERVICE_WSDL_LOCATION = url;
    }

    public EASLoginProxyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EASLoginProxyService() {
        super(EASLOGINPROXYSERVICE_WSDL_LOCATION, new QName("http://192.168.100.227:6888/ormrpc/services/EASLogin", "EASLoginProxyService"));
    }

    /**
     * @return
     *         returns EASLoginProxy
     */
    @WebEndpoint(name = "EASLogin")
    public EASLoginProxy getEASLogin() {
        return super.getPort(new QName("http://192.168.100.227:6888/ormrpc/services/EASLogin", "EASLogin"), EASLoginProxy.class);
    }

}
