CREATE VIEW C_BP_UF_BPFINANCING_DT1
AS
SELECT DT1."ID",DT1."MAINID",DT1."LASTPLAN",DT1."LASTHAPPEND",DT1."THISPLAN",DT1."DIFFERENCE",DT1."REMARKS",DT1."ACCOUNTID", ACCDT1.ACCOUNTNAME FROM UF_BPFINANCING_DT1 DT1 
INNER JOIN UF_BPACCOUNT_DT1 ACCDT1 ON ACCDT1.ID=DT1.ACCOUNTID;