CREATE VIEW C_BP_ACCOUNTTREE
AS
SELECT T1.ID, T1.ACCOUNTNAME, T1.DATAORDER, T1.ACCOUNTTYPE, T2.ID CHILDID, T2.ACCOUNTNAME CHILDACCOUNTNAME, T2.DATAORDER CHILDDATAORDER 
FROM UF_BPACCOUNT T1 
LEFT JOIN UF_BPACCOUNT_DT1 T2 ON T2.MAINID=T1.ID