-- 所有公司树视图
CREATE OR REPLACE VIEW C_BP_COMPANYTREE_ALL
AS
SELECT
	T2.ID, T2.SUBCOMPANYNAME, null PARENTID,
	T1.COMPANYBLOCK BLOCKID, T1.DATAORDER
FROM uf_BPCompany T1
INNER JOIN HRMSUBCOMPANY T2 ON T2.ID=T1.COMPANY