CREATE VIEW C_BP_COMPANYTREE
AS
SELECT
	T2.ID, T2.SUBCOMPANYNAME, null PARENTID,
	T1.COMPANYBLOCK BLOCKID, T1.DATAORDER, DT1.USERID
FROM uf_BPCompany T1
INNER JOIN HRMSUBCOMPANY T2 ON T2.ID=T1.COMPANY
INNER JOIN uf_BPCompany_DT1 DT1 ON DT1.MAINID=T1.ID