CREATE VIEW CV_BPCOMPANYPLANDT2_YEAR
AS
SELECT SUBSTR(M.YEARMONTH, 0, 4) YEAR, M.STATUS, M.COMPANY, DT.ACCOUNTID, SUM(DT.LASTPLAN) LASTPLAN, SUM(DT.LASTHAPPEND) LASTHAPPEND, SUM(DT.THISPLAN) THISPLAN, SUM(DT.DIFFERENCE) DIFFERENCE
FROM UF_BPCOMPANYPLAN_DT2 DT
INNER JOIN UF_BPCOMPANYPLAN M ON M.ID=DT.MAINID
GROUP BY M.COMPANY, DT.ACCOUNTID, SUBSTR(M.YEARMONTH, 0, 4), M.STATUS
