CREATE OR REPLACE VIEW CV_BPCOMPANYPLAN_DT1_UM AS
SELECT MAINID,LASTPLAN,LASTHAPPEND,THISPLAN,DIFFERENCE,1 AMOUNTTYPE FROM UF_BPCOMPANYPLAN_DT1
UNION
SELECT MAINID,LASTPLAN,LASTHAPPEND,THISPLAN,DIFFERENCE,1 AMOUNTTYPE FROM UF_BPCOMPANYPLAN_DT2
UNION
SELECT MAINID,LASTPLAN,LASTHAPPEND,THISPLAN,DIFFERENCE,2 AMOUNTTYPE FROM UF_BPCOMPANYPLAN_DT3
UNION
SELECT MAINID,LASTPLAN,LASTHAPPEND,THISPLAN,DIFFERENCE,2 AMOUNTTYPE FROM UF_BPCOMPANYPLAN_DT4
UNION
SELECT MAINID,LASTPLAN,LASTHAPPEND,THISPLAN,DIFFERENCE,2 AMOUNTTYPE FROM UF_BPCOMPANYPLAN_DT5