CREATE OR REPLACE VIEW CV_GROUPFUNDS_SUMMARY
AS
SELECT 
	CMS.LASTYEARMONTH,
	NVL(CMS.LASTMONTHBEGIN, 0) LASTMONTHBEGIN,
	NVL(CMS.THISMONTHPLAN, 0) THISMONTHPLAN,
	NVL(INA.THISPLAN, 0) INPLAN,
	NVL(INA.LASTHAPPEND, 0) INHAPPEND, 
	NVL(EXA.THISPLAN, 0) EXPLAN,
	NVL(EXA.LASTHAPPEND, 0) EXHAPPEND,
	(NVL(CMS.THISMONTHPLAN, 0) + NVL(INA.THISPLAN, 0) - NVL(EXA.THISPLAN, 0)) LASTMONTHENDPLN,
	(NVL(CMS.LASTMONTHBEGIN, 0) + NVL(INA.LASTHAPPEND, 0) - NVL(EXA.LASTHAPPEND, 0)) LASTMONTHENDHAP
FROM CV_GROUPFUNDS_CASH CMS
LEFT JOIN (
	SELECT AMT.LASTYEARMONTH, NVL(SUM(AMT.THISPLAN), 0) THISPLAN, NVL(SUM(AMT.LASTHAPPEND), 0) LASTHAPPEND
	FROM CV_GROUPFUNDS_AMOUNT AMT
	INNER JOIN UF_BPACCOUNT_DT1 ACC ON ACC.ID=AMT.ACCOUNTID
	WHERE ACC.MAINID IN (SELECT ACCOUNTID FROM UF_BPCONFIG UNPIVOT (ACCOUNTID FOR COLNAME IN (BUSSINCACCOUNT, FINANCEINCACCOUNT)) WHERE ISOPEN=1)
	GROUP BY AMT.LASTYEARMONTH) INA ON INA.LASTYEARMONTH=CMS.LASTYEARMONTH
LEFT JOIN (
	SELECT AMT.LASTYEARMONTH, NVL(SUM(AMT.THISPLAN), 0) THISPLAN, NVL(SUM(AMT.LASTHAPPEND), 0) LASTHAPPEND
	FROM CV_GROUPFUNDS_AMOUNT AMT
	INNER JOIN UF_BPACCOUNT_DT1 ACC ON ACC.ID=AMT.ACCOUNTID
	WHERE ACC.MAINID IN (SELECT ACCOUNTID FROM UF_BPCONFIG UNPIVOT (ACCOUNTID FOR COLNAME IN (BUSSEXPACCOUNT, FINANCEEXPACCOUNT, PROJECTEXPACCOUNT)) WHERE ISOPEN=1)
	GROUP BY AMT.LASTYEARMONTH) EXA ON EXA.LASTYEARMONTH=CMS.LASTYEARMONTH