-- 查询有效科目
CREATE OR REPLACE VIEW CV_GROUPFUNDS_ACCOUNT
AS
SELECT T1.ID, T1.ACCOUNTNAME, DT.ID IDL2, DT.ACCOUNTNAME ACCOUNTNAMEL2, DT.DATAORDER
FROM UF_BPACCOUNT_DT1 DT
INNER JOIN UF_BPACCOUNT T1 ON T1.ID = DT.MAINID
WHERE T1.ISOPEN=1 AND DT.ISOPEN=1;