-- 现金月初余额：本月计划额，CASH：现金
CREATE OR REPLACE VIEW CV_GROUPFUNDS_CASH
AS
SELECT SUM(LASTMONTHBEGIN) LASTMONTHBEGIN, SUM(THISMONTHPLAN) THISMONTHPLAN, T1.LASTYEARMONTH
FROM UF_BPCOMPANYPLAN T1 WHERE T1.STATUS=3
GROUP BY T1.LASTYEARMONTH;