CREATE OR REPLACE VIEW CV_PLAN_SUMMARY AS

SELECT
  CMS.LASTYEARMONTH, CMS.COMPANY, ORG.SUBCOMPANYNAME COMPANYNAME, RES.LASTNAME SUBMITNAME, CMS.SUBMITDATE, CMS.ID,
  NVL(CMS.THISMONTHPLAN, 0) LASTMONTHBEGIN,
  NVL(CMS.LASTMONTHBEGIN, 0) THISMONTHPLAN,  
  NVL(INA.THISPLAN, 0) INPLAN,
  NVL(INA.LASTHAPPEND, 0) INHAPPEND,
  NVL(EXA.THISPLAN, 0) EXPLAN,
  NVL(EXA.LASTHAPPEND, 0) EXHAPPEND,
  NVL(CMS.THISMONTHPLAN, 0)  + (NVL(INA.THISPLAN, 0) - NVL(EXA.THISPLAN, 0)) LASTMONTHENDPLN,
  NVL(CMS.LASTMONTHBEGIN, 0) + (NVL(INA.LASTHAPPEND, 0) - NVL(EXA.LASTHAPPEND, 0)) LASTMONTHENDHAP
FROM CV_PLANFUNDS_CASH CMS
LEFT JOIN (
  SELECT AMT.LASTYEARMONTH, NVL(SUM(AMT.THISPLAN), 0) THISPLAN, NVL(SUM(AMT.LASTHAPPEND), 0) LASTHAPPEND, COMPANY
  FROM CV_PLANFUNDS_AMOUNT AMT
  INNER JOIN UF_BPACCOUNT_DT1 ACC ON ACC.ID=AMT.ACCOUNTID
  WHERE ACC.MAINID IN (SELECT ACCOUNTID FROM UF_BPCONFIG UNPIVOT (ACCOUNTID FOR COLNAME IN (BUSSINCACCOUNT, inBussIncAccount)) WHERE ISOPEN=1)
  GROUP BY AMT.LASTYEARMONTH, AMT.COMPANY) INA ON INA.LASTYEARMONTH=CMS.LASTYEARMONTH AND CMS.COMPANY=INA.COMPANY
LEFT JOIN (
  SELECT AMT.LASTYEARMONTH, NVL(SUM(AMT.THISPLAN), 0) THISPLAN, NVL(SUM(AMT.LASTHAPPEND), 0) LASTHAPPEND, COMPANY
  FROM CV_PLANFUNDS_AMOUNT AMT
  INNER JOIN UF_BPACCOUNT_DT1 ACC ON ACC.ID=AMT.ACCOUNTID
  WHERE ACC.MAINID IN (SELECT ACCOUNTID FROM UF_BPCONFIG UNPIVOT (ACCOUNTID FOR COLNAME IN (BUSSEXPACCOUNT, INBUSSEXPACCOUNT, PROJECTEXPACCOUNT)) WHERE ISOPEN=1)
  GROUP BY AMT.LASTYEARMONTH, AMT.COMPANY) EXA ON EXA.LASTYEARMONTH=CMS.LASTYEARMONTH AND CMS.COMPANY=EXA.COMPANY
LEFT JOIN HRMSUBCOMPANY ORG ON ORG.ID=CMS.COMPANY
LEFT JOIN HRMRESOURCE RES ON RES.ID=CMS.SUBMITNAME