CREATE OR REPLACE VIEW CV_PLANFUNDS_AMOUNT AS
SELECT ACCOUNTID, NVL(SUM(LASTPLAN), 0) LASTPLAN, NVL(SUM(LASTHAPPEND), 0) LASTHAPPEND, NVL(SUM(THISPLAN), 0) THISPLAN, T1.LASTYEARMONTH, T1.COMPANY
FROM UF_BPCOMPANYPLAN_DT1 DT
INNER JOIN UF_BPCOMPANYPLAN T1 ON T1.ID=DT.MAINID WHERE T1.STATUS=3
GROUP BY DT.ACCOUNTID, T1.LASTYEARMONTH, T1.COMPANY
UNION
SELECT ACCOUNTID, NVL(SUM(LASTPLAN), 0) LASTPLAN, NVL(SUM(LASTHAPPEND), 0) LASTHAPPEND, NVL(SUM(THISPLAN), 0) THISPLAN, T1.LASTYEARMONTH, T1.COMPANY
FROM UF_BPCOMPANYPLAN_DT2 DT
INNER JOIN UF_BPCOMPANYPLAN T1 ON T1.ID=DT.MAINID WHERE T1.STATUS=3
GROUP BY DT.ACCOUNTID, T1.LASTYEARMONTH, T1.COMPANY
UNION
SELECT ACCOUNTID, NVL(SUM(LASTPLAN), 0) LASTPLAN, NVL(SUM(LASTHAPPEND), 0) LASTHAPPEND, NVL(SUM(THISPLAN), 0) THISPLAN, T1.LASTYEARMONTH, T1.COMPANY
FROM UF_BPCOMPANYPLAN_DT3 DT
INNER JOIN UF_BPCOMPANYPLAN T1 ON T1.ID=DT.MAINID WHERE T1.STATUS=3
GROUP BY DT.ACCOUNTID, T1.LASTYEARMONTH, T1.COMPANY
UNION
SELECT '15', NVL(SUM(LASTPLAN), 0) LASTPLAN, NVL(SUM(LASTHAPPEND), 0) LASTHAPPEND, NVL(SUM(THISPLAN), 0) THISPLAN, T1.LASTYEARMONTH, T1.COMPANY
FROM UF_BPCOMPANYPLAN_DT4 DT
INNER JOIN UF_BPCOMPANYPLAN T1 ON T1.ID=DT.MAINID WHERE T1.STATUS=3
GROUP BY T1.LASTYEARMONTH, T1.COMPANY
UNION
SELECT ACCOUNTID, NVL(SUM(LASTPLAN), 0) LASTPLAN, NVL(SUM(LASTHAPPEND), 0) LASTHAPPEND, NVL(SUM(THISPLAN), 0) THISPLAN, T1.LASTYEARMONTH, T1.COMPANY
FROM UF_BPCOMPANYPLAN_DT5 DT
INNER JOIN UF_BPCOMPANYPLAN T1 ON T1.ID=DT.MAINID WHERE T1.STATUS=3
GROUP BY DT.ACCOUNTID, T1.LASTYEARMONTH, T1.COMPANY
