CREATE OR REPLACE VIEW CV_PLANFUNDS_CASH AS
SELECT T1.COMPANY,T1.YEARMONTH, SUM(LASTMONTHBEGIN) LASTMONTHBEGIN, SUM(THISMONTHPLAN) THISMONTHPLAN, T1.LASTYEARMONTH, T1.SUBMITNAME, T1.SUBMITDATE, T1.ID
FROM UF_BPCOMPANYPLAN T1 WHERE T1.STATUS=3
GROUP BY T1.LASTYEARMONTH, T1.COMPANY, T1.SUBMITNAME, T1.SUBMITDATE, T1.ID,T1.YEARMONTH
