CREATE OR REPLACE VIEW CV_PLANSUMMARY AS
SELECT
	T1.LASTYEARMONTH YEARMONTH, COM.SUBCOMPANYNAME,COM.id companyId, SBU.LASTNAME, T1.SUBMITDATE, T1.ID,
	SUM(CASE WHEN DT1.AMOUNTTYPE=1 THEN DT1.LASTPLAN ELSE 0 END) PLANAMOUNTIN,
	SUM(CASE WHEN DT1.AMOUNTTYPE=1 THEN DT1.LASTHAPPEND ELSE 0 END) SPENDAMOUNTIN,
  SUM(CASE WHEN DT1.AMOUNTTYPE=2 THEN DT1.LASTPLAN ELSE 0 END) PLANAMOUNTEXT,
  SUM(CASE WHEN DT1.AMOUNTTYPE=2 THEN DT1.LASTHAPPEND ELSE 0 END) SPENDAMOUNTEXT
FROM UF_BPCOMPANYPLAN T1
LEFT JOIN CV_BPCOMPANYPLAN_DT1_UM DT1 ON DT1.MAINID=T1.ID
LEFT JOIN HRMSUBCOMPANY COM ON COM.ID=T1.COMPANY
LEFT JOIN HRMRESOURCE SBU ON SBU.ID=T1.SUBMITNAME
WHERE T1.STATUS=3
GROUP BY T1.LASTYEARMONTH, COM.SUBCOMPANYNAME, COM.ID,SBU.LASTNAME, T1.SUBMITDATE, T1.ID
ORDER BY T1.LASTYEARMONTH DESC