-- ----------------------------
-- Table structure for ECST_REQUESTLOG
-- ----------------------------
DROP TABLE ECST_REQUESTLOG;

CREATE TABLE ECST_REQUESTLOG (
	REQUESTID NUMBER NULL ,
	OPERATOR VARCHAR2(255 BYTE) NULL ,
	LASTNAME VARCHAR2(255 BYTE) NULL ,
	DEPARTMENTNAME VARCHAR2(255 BYTE) NULL ,
	NODENAME VARCHAR2(255 BYTE) NULL ,
	REMARK LONG NULL ,
	OPERATEDATE VARCHAR2(10 BYTE) NULL ,
	OPERATETIME VARCHAR2(8 BYTE) NULL ,
	RECEIVEDPERSONS CLOB NULL ,
	LOGTYPE VARCHAR2(255 BYTE) NULL ,
	BILLCODE VARCHAR2(255 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE
;