-- 项目类合同录入
ALTER TABLE FORMTABLE_MAIN_55 MODIFY hetlx VARCHAR2(20);
ALTER TABLE FORMTABLE_MAIN_55 MODIFY hetxz VARCHAR2(20);
ALTER TABLE FORMTABLE_MAIN_55 MODIFY bib VARCHAR2(20);
ALTER TABLE FORMTABLE_MAIN_55 MODIFY zaojxz VARCHAR2(30);
ALTER TABLE FORMTABLE_MAIN_55 MODIFY bengbjedx VARCHAR2(60);
ALTER TABLE FORMTABLE_MAIN_55 MODIFY yuanbjedx VARCHAR2(60);
ALTER TABLE FORMTABLE_MAIN_55 MODIFY xingcfs VARCHAR2(20);