-- 新员工录用申请
ALTER TABLE FORMTABLE_MAIN_30_DT1 MODIFY xingb VARCHAR2(6);
ALTER TABLE FORMTABLE_MAIN_30_DT1 MODIFY xingzzj VARCHAR2(30);
ALTER TABLE FORMTABLE_MAIN_30_DT1 MODIFY zhiw VARCHAR2(30);
ALTER TABLE FORMTABLE_MAIN_30_DT1 MODIFY xuel VARCHAR2(10);