CREATE TABLE GREEDC_PRO_EXP_BUDGET (
  SEQ_NO           INTEGER PRIMARY KEY,
  REQUEST_ID       INTEGER,
  PROJECT_ID       VARCHAR2(30),
  PROJECT_NAME     VARCHAR2(100),
  PAY_CO           VARCHAR2(100),
  ACC_PAYABLE      NUMBER(15, 2),
  PROPORTION       VARCHAR2(50),
  PAY_TOTAL        NUMBER(15, 2),
  CON_NUM          INTEGER,
  STATISTICAL_DEPT VARCHAR2(100),
  YEAR_            VARCHAR2(10),
  MONTH_           VARCHAR2(10)
);
