DROP TABLE GREEDC_DATAGRID_FIELD;

CREATE TABLE GREEDC_DATAGRID_FIELD (
  SEQNO      INTEGER PRIMARY KEY,
  BILLID     INTEGER NOT NULL,
  FTITLE     VARCHAR2(50),
  FFIELD     VARCHAR2(20),
  WIDTH      INTEGER,
  ALIGN      VARCHAR2(10),
  FORMATTER  VARCHAR2(50),
  FORDER     NUMBER(15, 2)
);

INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('2', '-44', 'SEQNO', 'SEQNO', NULL, NULL, NULL, NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('3', '-44', 'REQUESTID', 'REQUESTID', NULL, NULL, NULL, NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('4', '-44', 'FPER001', 'FPER001', NULL, NULL, NULL, NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('5', '-44', 'FPER003', 'FPER003', NULL, NULL, NULL, NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('6', '-44', 'FPER025', 'FPER025', NULL, NULL, NULL, NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('7', '-44', 'ORGNUMBER', 'ORGNUMBER', NULL, NULL, NULL, NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('8', '-44', 'ORGNAME', 'ORGNAME', NULL, NULL, NULL, NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('9', '-44', 'FFSAL210', 'FFSAL210', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('10', '-44', 'FFSAL212', 'FFSAL212', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('11', '-44', 'FFSAL211', 'FFSAL211', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('12', '-44', 'FFSAL214', 'FFSAL214', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('13', '-44', 'FFSAL378', 'FFSAL378', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('14', '-44', 'FFSAL397', 'FFSAL397', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('15', '-44', 'FFSAL213', 'FFSAL213', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('16', '-44', 'FFSAL216', 'FFSAL216', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('17', '-44', 'FSAL014', 'FSAL014', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('18', '-44', 'FFSAL217', 'FFSAL217', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('19', '-44', 'FFSAL208', 'FFSAL208', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('20', '-44', 'FFSAL209', 'FFSAL209', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('21', '-44', 'FFWEL331', 'FFWEL331', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('22', '-44', 'FFSAL201', 'FFSAL201', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('23', '-44', 'FFSAL203', 'FFSAL203', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('24', '-44', 'FSAL006', 'FSAL006', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('25', '-44', 'FWEL002', 'FWEL002', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('26', '-44', 'FFSAL349', 'FFSAL349', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('27', '-44', 'FSAL007', 'FSAL007', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('28', '-44', 'FSAL004', 'FSAL004', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('29', '-44', 'FSAL005', 'FSAL005', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('30', '-44', 'FWEL004', 'FWEL004', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('31', '-44', 'FSAL001', 'FSAL001', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('32', '-44', 'FSAL029', 'FSAL029', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('33', '-44', 'FSAL027', 'FSAL027', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('34', '-44', 'FFSAL248', 'FFSAL248', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('35', '-44', 'FWEL013', 'FWEL013', NULL, 'right', 'GREEDC.toMoney', NULL);
INSERT INTO "ECOLOGY"."GREEDC_DATAGRID_FIELD" ("SEQNO", "BILLID", "FTITLE", "FFIELD", "WIDTH", "ALIGN", "FORMATTER", "FORDER") VALUES ('36', '-44', 'FWEL016', 'FWEL016', NULL, 'right', 'GREEDC.toMoney', NULL);