DROP VIEW UF_BPCOMPANY_MYTREE
GO

CREATE VIEW UF_BPCOMPANY_MYTREE
AS
SELECT T2.ID UNITID, NULL PARENTUNITID, T2.SUBCOMPANYNAME, DT1.USERID
FROM UF_BPCOMPANY T1 INNER JOIN HRMSUBCOMPANY T2 ON T2.ID=T1.PARENTUNITID
INNER JOIN UF_BPCOMPANY_DT1 DT1 ON DT1.MAINID=T1.ID
UNION
SELECT T1.UNITID, T1.PARENTUNITID, T2.SUBCOMPANYNAME, DT1.USERID
FROM UF_BPCOMPANY T1 INNER JOIN HRMSUBCOMPANY T2 ON T2.ID=T1.UNITID
INNER JOIN UF_BPCOMPANY_DT1 DT1 ON DT1.MAINID=T1.ID;