-- 内部异动申请
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='varchar2(20)', FIELDHTMLTYPE=1, TYPE=1 WHERE ID=6448;
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='integer', FIELDHTMLTYPE=3, TYPE=24 WHERE ID=6447;
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='integer', FIELDHTMLTYPE=3, TYPE=1 WHERE ID=6442;

-- 试用期转正申请
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='varchar2(20)', FIELDHTMLTYPE=1, TYPE=1 WHERE ID=6635;
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='varchar2(30)', FIELDHTMLTYPE=1, TYPE=1 WHERE ID=6638;
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='varchar2(30)', FIELDHTMLTYPE=1, TYPE=1 WHERE ID=6639;

-- 合同到期续签申请
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='integer', FIELDHTMLTYPE=3, TYPE=1 WHERE ID=6565;
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='varchar2(20)', FIELDHTMLTYPE=1, TYPE=1 WHERE ID=6570;

-- 薪酬发放审批表单
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='integer', FIELDHTMLTYPE=3, TYPE=1 WHERE ID=6784;
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='varchar2(20)', FIELDHTMLTYPE=1, TYPE=1 WHERE ID=6790;
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='varchar2(20)', FIELDHTMLTYPE=1, TYPE=1 WHERE ID=6791;

-- 薪酬调整审批
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='integer', FIELDHTMLTYPE=3, TYPE=1 WHERE ID=6605;

-- 新员工录用申请
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='varchar2(6)', FIELDHTMLTYPE=1, TYPE=1 WHERE ID=6427;
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='varchar2(30)', FIELDHTMLTYPE=1, TYPE=1 WHERE ID=6438;
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='varchar2(30)', FIELDHTMLTYPE=1, TYPE=1 WHERE ID=6439;
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='varchar2(10)', FIELDHTMLTYPE=1, TYPE=1 WHERE ID=6431;

-- 项目类合同录入
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='varchar2(20)', FIELDHTMLTYPE=1, TYPE=1 WHERE ID=7068;
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='varchar2(20)', FIELDHTMLTYPE=1, TYPE=1 WHERE ID=7069;
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='varchar2(20)', FIELDHTMLTYPE=1, TYPE=1 WHERE ID=7070;
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='varchar2(20)', FIELDHTMLTYPE=1, TYPE=1 WHERE ID=7084;
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='varchar2(30)', FIELDHTMLTYPE=1, TYPE=1 WHERE ID=7088;
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='varchar2(60)', FIELDHTMLTYPE=1, TYPE=1 WHERE ID=7078;
UPDATE WORKFLOW_BILLFIELD SET FIELDDBTYPE='varchar2(60)', FIELDHTMLTYPE=1, TYPE=1 WHERE ID=7081;
